### ISSUE TITLE
sprites[index] returns null

### ISSUE THREAD

**Issue by mimoguz** [mimoguz/tripeaks-gdx#22]
Exception in thread "main" java.lang.NullPointerException: sprites[index] must not be null
	at ogz.tripeaks.graphics.IndexedSprite.get(sprites.kt:45)
	at ogz.tripeaks.game.CardDrawingStrategy$Strategies$BackHidden.drawStacked(CardDrawingStrategy.kt:94)
	at ogz.tripeaks.game.StackView.draw(StackView.kt:41)
	at ogz.tripeaks.screens.RenderHelper.render(RenderHelper.kt:60)
	at ogz.tripeaks.screens.GameScreen.render(GameScreen.kt:110)
	at ktx.app.KtxGame.render(game.kt:55)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at ogz.tripeaks.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.kt:15)
	at ogz.tripeaks.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.kt)

**Comment by mimoguz** [comment]
GdxTexturePacker converts number post-fixes to indices. Fixed.
